from tkinter import *
VentanaPrincipal = Tk()
FramePrincipal = Frame(VentanaPrincipal, width = 800, height = 400)
FramePrincipal.pack()
MiNombre = StringVar()

CuadroNombre = Entry(FramePrincipal, textvariable = MiNombre)
CuadroNombre.grid(row = 0, column = 1, padx = 10, pady = 10)
CuadroNombre.config(fg = "red", justify = "center")
CuadroApellido = Entry(FramePrincipal)
CuadroApellido.grid(row = 1, column = 1, padx = 10, pady = 10)
CuadroApellido.config(fg = "red", justify = "center")
CuadroDireccion = Entry(FramePrincipal)
CuadroDireccion.grid(row = 2, column = 1, padx = 10, pady = 10)
CuadroDireccion.config(fg = "red", justify = "center")
CuadroPass = Entry(FramePrincipal)
CuadroPass.grid(row = 3, column = 1, padx = 10, pady = 10)
CuadroPass.config(show = "*", justify = "center")
CuadroComentario = Text(FramePrincipal, width = 15, height = 5)
CuadroComentario.grid(row = 4, column = 1, padx = 10, pady = 10)
Scrollvertical = Scrollbar(FramePrincipal, command = CuadroComentario.yview)
Scrollvertical.grid(row = 4, column = 2, sticky = "nsew")
CuadroComentario.config(yscrollcommand = Scrollvertical.set)
NombreLabel = Label(FramePrincipal, text="Nombre: ")
NombreLabel.grid(row = 0, column = 0, sticky = "e", padx = 50, pady = 10)
ApellidoLabel = Label(FramePrincipal, text="Apellido: ")
ApellidoLabel.grid(row = 1, column = 0, sticky = "e", padx = 50, pady = 10)
DireccionLabel = Label(FramePrincipal, text="Direccion: ")
DireccionLabel.grid(row = 2, column = 0, sticky = "e", padx = 50, pady = 10)
PassLabel = Label(FramePrincipal, text="Contrasenia: ")
PassLabel.grid(row = 3, column = 0, sticky = "e", padx = 50, pady = 10)
ComentarioLabel = Label(FramePrincipal, text="Comentario: ")
ComentarioLabel.grid(row = 4, column = 0, sticky = "e", padx = 50, pady = 10)

def CodigoBoton():
    MiNombre.set("Eduardo")

BotonEnvio = Button(VentanaPrincipal, text = "Enviar", command = CodigoBoton)
BotonEnvio.pack()

VentanaPrincipal.mainloop()